---
arrowParens: avoid
bracketSpacing: true
endOfLine: lf
jsxBracketSameLine: false
jsxSingleQuote: false
printWidth: 100
quoteProps: consistent
semi: false
singleQuote: false
tabWidth: 2
trailingComma: all
