---
arrowParens: avoid
bracketSpacing: false
endOfLine: lf
jsxBracketSameLine: false
jsxSingleQuote: false
printWidth: 80
quoteProps: consistent
semi: false
singleQuote: false
tabWidth: 2
trailingComma: es5
